### ISSUE TITLE
account_invoice_validation_workflow v8 - Lost buttons

### ISSUE THREAD

**Issue by dolcey** [OCA/account-invoicing#115]
When installing the module, the buttons are lost when you see the bill:   "Send to Email", "Register payment" and "Reintegrating invoice".

To correct this, I uninstall the module, and buttons appear again.

I think a budget, do valid, confirmed the sale, and I believe the bill, so far, so good, the problem is when I go to validate it, to click on "Validate" does nothing. It is like nothing to validate. From here I can not pass.

They could give me a help please?

Excuse my translation.

**Comment by sandrafig** [comment]
I don't know what the purpose of this module is.

When I create a new invoice, only two buttons show up: **Cancel invoice** and **To Validation**. 
If I click on **To Validation**, the state of the invoice changes to "To Validate" but I cannot validate it because I only have one button, which is **"Invoice To Send"**, so I click on it and now I cannot send it by email but I can finally Validate it.

I don't get what the purpose is, if I cannot validate inmediately after setting it to "To Validate", and why does it say **Invoice To Send**, if the button **send by email** doesn't show up anywhere.

I'm confused.

**Comment by dolcey** [comment]
Sandra, el propósito hasta donde lo he usado es agregar más pasos a la validación, y así evitar una validación accidental.

El botón de enviar por correo se ha perdido por falta de una linea en la vista heredad añadida por el módulo, en mi caso, tuve que crear otra heredada de la que crea el módulo y colocar el botón.

Espero esta información te sirva.
