### ISSUE TITLE
Account Invoice Triple Discount does not compute correctly price_subtotal

### ISSUE THREAD

**Issue by cscocca** [OCA/account-invoicing#1240]
The module does not compute correctly the `price_subtotal` field because the price rounding feature.

## Module
account_invoice_triple_discount

## Describe the bug
When the invoice has a price and a discount (just one discount can reproduce the issue) that produce a discounted price with more decimals than price rounding setting so the `price_subtotal` is wrong.

## To Reproduce
An example is:
qty           price            discount    discount2      discount3     subtotal
9950        0.139              15%            0                   0               1176.09

but the right subtotal is **1175.59** because 0.139 minus 15% is 0.11815 * 9950 = 1175.5925 -> Rounded = 1175.59.

**Affected versions**:

- [x] 12.0

**Comment by legalsylvain** [comment]
Could you add in a PR a test that is failing ?
Thanks !

**Comment by cscocca** [comment]
Just added
https://github.com/OCA/account-invoicing/pull/1242

**Comment by ramiadavid** [comment]
@legalsylvain @c-amara 

I have the same problem, even using only Odoo's default discount field and the problem is here
```
        for line in self.line_ids:
            aggregated_discount = line._compute_aggregated_discount(line.discount)
            old_values_by_line_id[line.id] = {
                "price_unit": line.price_unit,
                "discount": line.discount,
            }
            price_unit = line.price_unit * (1 - aggregated_discount / 100)
            line.update({"price_unit": price_unit, "discount": 0})**
```
To calculate the taxes here the unit price with the aggregated discounts is computed, but when saving the value in the line Odoo rounds to the decimals by default and this produces an inaccuracy when calculating the taxes and the base especially when the line contains many units.
