### ISSUE TITLE
[10][account_invoice_refund_link] dont link original invoice when create from Sales > Invoicing > Sales to invoice

### ISSUE THREAD

**Issue by JuanjoA** [OCA/account-invoicing#563]
Steps to reproduce:
1/ Configure products to invoice delivered products.
2/ Create sale order and confirm.
3/ Transfer the delivery.
4/ Generate invoice from Sales > Invoicing > Sales to invoice and validate.
5/ Return transfer and check to refund in lines.

Now:
4.1/ if we create the refund invoice from the original invoice, we have both invoices linked.
4.2/ if we create the refund invoice from Sales > Invoicing > Sales to invoice we dont have the invoices linked.

Can you guys confirm this? 
Thanks

**Comment by pedrobaeza** [comment]
Yes, this is the expected behavior, as the refund hasn't been created from the invoice. Which invoice do you link? Imagine all the possible use cases that you can find...

**Comment by JuanjoA** [comment]
Thanks @pedrobaeza , we can link the invoice related to the return, although I suppose that will require  _stock_picking_invoice_link_
If not, we will required to do the same job twice, once for the return transfer and once for the invoice.

**Comment by pedrobaeza** [comment]
The problem is that you can have split normal invoices, with different quantities, and so on, so it's almost impossible to get accurate results, but not only that: a refund coming from a return can be considered as rectifying normal invoice? There are fiscal legal edges there...

If you are affected, you can always link manually the invoice, or I'm opened to suggestions on this.

**Comment by JuanjoA** [comment]
Yes, it's a complex thing.
