### ISSUE TITLE
 [10.0/11.0/12.0][account_invoice_supplier_ref_unique] The invoice number for the supplier already exists

### ISSUE THREAD

**Issue by pedroortega-punt** [OCA/account-invoicing#659]
When a supplier restarts the fiscal year and changes its counters not taking into account the fiscal year in its numbering and sends us the same invoice number the following year, when registering odoo it indicates that it is repeated. You should only check those numbers annually.

Example:

Year 2019, supplier invoice number 1

Year 2020, supplier invoice number 1

**Comment by legalsylvain** [comment]
I don't think so.
Invoice number should be unique. I think the supplier is wrong.

In any case this module doens't fit with your needs, and can not be fixed easely. The reason is that fiscal years of your supplier can be different that the fiscal year of your company in Odoo. And you have no way to know it.
